services:
  - type: web
    name: findify-fastapi
    env: python

    rootDirectory: backend

    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"

    envVars:
      - key: MONGO_URL
        value: mongodb+srv://Navneet:Navneet@cluster0.ci1bguk.mongodb.net/?retryWrites=true&w=majority

      - key: DB_NAME
        value: findify_db

      - key: CORS_ORIGINS
        value: https://findify-document-search.vercel.app,http://localhost:3000
