services:
  - type: web
    name: findify-backend
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "chmod +x startup.sh && ./startup.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.15
      - key: TOKENIZERS_PARALLELISM
        value: false